### ISSUE TITLE
Expression widget - add numeric scores to bars

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1014]
From @kkarra 

> I have not been able to make the raw score appear on mouse-over in the chart. It looks like that data is not available to the displayer. I tried all sorts of things, but, did not succeed. 

![exp](https://cloud.githubusercontent.com/assets/1663057/7722252/60a28890-fed6-11e4-98c6-e9401df55910.png)

**Comment by julie-sullivan** [comment]
Here is where the query results are handled:

https://github.com/intermine/intermine/blob/beta/bio/webapp/src/org/intermine/bio/web/displayer/FlyBaseExpressionDisplayer.java#L124-L133

It looks like even though the score is in the query, it's not being added to the results. That isn't very clever! Add the score to the results.

Once you have the results, you can add them to the tooltip on the JSP:

https://developers.google.com/chart/interactive/docs/roles#tooltiprole

**Comment by kkarra** [comment]
Hi Julie,

Finally, with no help from any descriptive error, figured that the problem was the fact that I was not casting the score properly.

 String expressionLevel =  (String) row.get(2).getField();
vs
String expressionScore = ((Float) row.get(2).getField()).toString();

I now see the scores avaliable to the jsp displayer code!

Thanks,
-Kalpana
