### ISSUE TITLE
Pathways displayer is broken

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1126]
From @kkarra

Gives me this error about jquery version..which I thought is odd as things should have been packaged properly in CDN?

```

Pathways from Other Mines

Pathway data from other Mines for homologues of this gene.
This app requires jQuery 2.x.x

```

**Comment by julie-sullivan** [comment]
Put the displayer back on beta temporarily: 8af6c29415b0825be7ea6737eaf1f687caaebf07

**Comment by yochannah** [comment]
Investigating now. Initial notes: this is not a jquery version bug - the version in question is 2.0.3 - but the code to handle errors has "This app requires jQuery 2.x.x" hardcoded into it, so it'll display for any JS error.

**Comment by yochannah** [comment]
Ok, this is an odd one. 

The app was broken due to dependency versions being loaded incorrectly by the loader. So even if the global.web.properties specifies version 1.4 of underscore, 1.7 loads instead. And [1.7 introduces several breaking changes](http://stackoverflow.com/questions/25570559/template-error-upgrading-to-underscore-1-7). The fact that the wrong version is being loaded hasn't been resolved yet and maybe needs its own ticket.

That said, I've made the pathways displayer compatible with 1.7+ versions of underscore, and it is still backward compatible with older versions of underscore as well. I'll do a pull request in a minute.

**Comment by julie-sullivan** [comment]
Can you assign this to me with instructions on how to test? I'll then forward to @kkarra so she can fix her install.

**Comment by yochannah** [comment]
yeah I didn't intend to close it - I wrote "fixes (url)" in the comments of a different pull and it auto-closed. oops.

**Comment by yochannah** [comment]
https://github.com/intermine/intermine/pull/1129 should fix it but we will need to change it to the proper cdn when it goes out of the beta branch

**Comment by julie-sullivan** [comment]
@yochannah Can you re-add your pull request but merge on the dev branch instead? Thanks!

**Comment by julie-sullivan** [comment]
Fixed but slow, due to CORS issues
