### ISSUE TITLE
GO widget download error in Safari

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1166]
From @akvallejos

> When I try to download the results from the GO list enrichment widget I get a browser error.

This is on humanmine. I can't replicate it on Chrome or Firefox so I am assuming this is Safari-specific. We've had this problem before apparently. #331

**Comment by julie-sullivan** [comment]
Also the view results in humanmine doesn't seem to be working but it's fine in flymine.

**Comment by yochannah** [comment]
This problem appears to be due to a dependency bug: https://github.com/eligrey/FileSaver.js/issues/12 luckily, recent versions fix it. I'll create a pull request that points to the correct dependency version in intermine, but if anyone wants to access the fix sooner all they need to do is point to a recent version of filesaver.js here: https://github.com/intermine/intermine/blob/dev/intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties#L126 and redeploy.

**Comment by yochannah** [comment]
This will be fixed by https://github.com/intermine/intermine/pull/1170. Note the CDN merge dependency.

**Comment by julie-sullivan** [comment]
@akvallejos Can you test this fix on beta flymine? I will push to humanmine next week.

**Comment by akvallejos** [comment]
@julie-sullivan Worked for me on FlyMine (Chrome on OS X)
