### ISSUE TITLE
Can't share lists with google logins

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1174]
From @akvallejos

> I am trying to share a list with another user. We both signed up through Google Authentication. When I try to share the list the site tells me that the user is not found.

**Comment by julie-sullivan** [comment]
It looks like we store the token that gmail gives us, not the actual gmail address (or password obviously). Not sure how to solve this.

**Comment by joshkh** [comment]
This was affected by the recent fix for the Google API bug. It works with some caveats (more on that below).

Tested:

1. Logged in with google account A.
2. Logged in with google account B.
3. Shared list from account A to account B.
4. B can see list shared from A.

There are some gotchas:

1. Users share lists with other users using a Public Name found in MyMine. For oAuth2 users we populate this with a preferred name, then email address.

2. If the sharee does not have a public name then a list can't be shared with them. I'd wager that people instinctual use a sharee's email address which is not always the right value.

3. When a sharer shares a list with another Google user they see their GoogleID in the share list.
![image](https://cloud.githubusercontent.com/assets/4752532/25656016/09fd9ce0-2fef-11e7-970e-8eea02c57a0d.png)

Actions to be taken:

Gotcha 1) This is bad design and should be implemented better in BlueGenes. I don't think it's worth redesigning in the current UI.

Gotcha 2) We should populate a user's Public Name using their email address instead of their preferred name. They can change it if they prefer something else.

Gotcha 3) We should display a user's Alias rather than their username. This is worth implementing in the current UI.

**Comment by joshkh** [comment]
2. has been implemented.
3. will require some redesign. See future enhancement #1582
