### ISSUE TITLE
Cytoscape: details not showing up for YeastMine

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1207]
From @kkarra

```
How do you make ‘Gene details’ appear in the box on the right on the new fancy interaction displayer?
It looks good and works now for yeastmine too! Thanks!

http://yeastmine-test.yeastgenome.org/yeastmine-dev/begin.do

try URA4
```

**Comment by yochannah** [comment]
So it looks like the yeastmine interaction model is a little bit different from the fly/human model - mostly that there are a lot of self-interactions, and that interactions don't use `role2` or `participant2.name`. I think I've compensated for it now - does this look alright? http://dry-headland-7948.herokuapp.com/ If it does I'll generate version 1.0.3 for the cdn.

**Comment by julie-sullivan** [comment]
is there a way to make this work for all models?

**Comment by kkarra** [comment]
Yo, this looks fine. Please go ahead. Just curious, if one can add other columns to the display by config? 

Julie, do let me know if there is some aspect of interactions model that still needs to be fixed because I do want it to be the same as fly/human. When I loaded complexes, there is a bit of straddling of old and new ways for regular interactions vs complexes.

**Comment by julie-sullivan** [comment]
@kkarra I think role2 and participant2.name are always empty. Do you know why that might be the case?
