### ISSUE TITLE
XenMine: GO is missing

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1219]
I am seeing the same error as this thread..

http://mail.intermine.org/pipermail/dev/2013-September/002629.html

```
11/11/15,10:02:45 ERROR org.intermine.webservice.server.core.TableRowIterator 
    - Couldn't find any paths for org.intermine.model.bio.GOAnnotation from amongst 
[Gene.primaryIdentifier, Gene.symbol, Gene.name, Gene.goAnnotation.ontologyTerm.identifier, 
Gene.goAnnotation.ontologyTerm.name, Gene.goAnnotation.ontologyTerm.namespace, 
Gene.organism.shortName, Gene.goAnnotation.evidence.withText, 
Gene.goAnnotation.evidence.code.code, Gene.goAnnotation.evidence.publications.pubMedId]


```

**Comment by julie-sullivan** [comment]
@kkarra Does this happen in dev-XenMine? With the latest code? We had some CORS issues that were causing the model to be cached. See #1124.

But that was fixed in 1.6 so likely not the issue.

What are the symptoms? When do you see this error? When looking at the report page? Querying for GO (on the live site) seems fine but GO doesn't show up on the report page.

**Comment by kkarra** [comment]
I switched it back (thinking it probably had to do with new GO annotation files I got).
Will get back to this if it is not a data issue

**Comment by kkarra** [comment]
Looks like that error happens in 1.5 and does not seem to effect results table(?) saw it in YM on 1.5 as well.

The problem with XenMine GO annot missing was solved by having the right integration keys in place. 
(was trying to merge repos so that yeastmine and xenmine are in one - but how does one deal with different mines needing different integration keys?? looks like this is not an issue for others..)

Can close this.
