### ISSUE TITLE
Publication Enrichment - download fails on NULL pubmed ID

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1274]
From @kkarra

Publication Enrichment widget will do nothing upon hitting ‘Download’ for this list of genes. (the example List works fine).

```
With regards to YeastMine, I'll just like to report a bug associated with exporting
the results from the Publication Enrichment tool. It fails to export the results if 
one of the entry has a NULL pubmed ID. I am able to export after I click select 
all entries except for the offending entry. I have included a list of genes as a 
test case below. The line that went wrong had the following result: Literature: 
Yeast ribosomal proteins: Electrophoretic analysis in four two-dimensional 
gel systems--Correlation of nomenclatures Pubmed ID: [null] p-value: 
1.171756e-11 Matches: 22 YDL133C-A YDR418W YDR447C YDR450W 
YER117W YGL077C YGL103W YGR118W YHR010W YHR141C YHR143W-A 
YJL134W YJL190C YJR094W-A YKR057W YLR075W YLR332W YLR342W-A 
YLR367W YML026C YMR143W YMR221C YMR230W YMR241W YNL210W 
YOL092W YOR096W YOR196C YOR234C YOR293W YOR369C YPR132W 
```

This smart user figured out that excluding null pubmedID entries from the widget makes it work. (search for null in page and find those rows in the widget)

So, it looks like publications that do not have a PMID are still used for enrichment, which is good if it is working correctly. I am not sure how/why that is  though...enrichIdentifier=“publications.pubMedId”  <--- I thought this config would probably not allow that..?  

Interestingly, if I ‘View’ results on the widget and summarize on PMID, I do not see any rows that have a null PMID. So it seems like View is filtering those out? If so, should Download do the same? Ideally view and download both will show and export null PMID rows as well..

**Comment by yochannah** [comment]
I've successfully managed to replicate this with the test model. At initial glance it looks like this is a clientside issue: there is a successful post request to the server when you try to download a list with the culprit null item selected - and the exact same number of lines in the server response when the culprit _isn't_ selected. 

Given the consistent server behaviour, it's probably client side processing getting stuck trying to process the null value. I'll try and see what's catching it out next week.

**Comment by julie-sullivan** [comment]
@yochannah YeastMine is enriching on publication title not pubmedID, which is why we've never seen this before:
https://github.com/yeastgenome/intermine/blob/master/yeastmine/webapp/resources/webapp/WEB-INF/webconfig-model.xml#L659

**Comment by kkarra** [comment]
Looks like that bit of config is same as FlyMine..
https://github.com/intermine/intermine/blob/master/flymine/webapp/resources/webapp/WEB-INF/webconfig-model.xml
Not sure what the difference between enrich vs enrichIdentifier is..will see if I can find some doc

**Comment by julie-sullivan** [comment]
@kkarra That attribute is what's analysed. FlyMine sets that value as pubmed ID, so of course we are never going to have NULL pubmed IDs. That's why this bug was never found before. That's all I meant. Does that make sense? It's not relevant for you, I was just telling @yochannah because I had been worried that the Java code was at fault not realising our config was different.

**Comment by yochannah** [comment]
ok, I've found the line in the widget enrichment which goes goes wrong. Question @julie-sullivan @kkarra - is the attached file a reasonable way of handling it? See the last line, XML leader. (don't worry about the other inappropriate new lines, the test model I'm using to replicate the situation is a bit tricky).

I had to change the file extension to .txt rather than tsv to get it to upload. 

[Employee List (Wed Jan 13 2016 11-22-31 GMT+0000 (GMT)) contractor_enrichment (9).txt](https://github.com/intermine/intermine/files/88858/Employee.List.Wed.Jan.13.2016.11-22-31.GMT.0000.GMT.contractor_enrichment.9.txt)

**Comment by kkarra** [comment]
sorry, I am not sure how to comment on the attached file. Which line in widget enrichment is the one that needs fixing? thanks!

**Comment by yochannah** [comment]
Sorry, looking back at what I posted it made sense in my head at the time but I can see why it might be incredibly unclear. It was a bit tricky for me to replicate the problem because we don't have any null publication identifiers in our human/fly data sets, so I used our test "employee" data model instead.

We'll need to release a new version of the list widgets enrichment script (https://github.com/intermine/CDN/tree/master/js/intermine/apps-c/list-widgets/) to handle null values, and I wanted to check that the workaround I've implemented to stop it choking on nulls was a reasonable way of handling things. Line 71 of the attached file is how I imagine enrichment of the sample list you provided might look with the workaround in place (mostly, it says "n/a null value"). If it looks ok, I'll release version 2.1.3 to our test CDN so you can test it out yourself on yeast?

[Gene list for S. cerevisiae 2 Feb 2016 9.17 publication_enrichment.txt](https://github.com/intermine/intermine/files/113643/Gene.list.for.S.cerevisiae.2.Feb.2016.9.17.publication_enrichment.txt)

I hope that makes more sense! Let me know if I'm still being unclear, and sorry again!

**Comment by kkarra** [comment]
no problem, I wasn't super clear either. Yes, that workaround (having n/a null value) sounds good!  Let me know when you release, I can check it out and test it. thanks!!

**Comment by yochannah** [comment]
Okay, it's checked in to our dev branch as version 2.1.3: 

https://github.com/intermine/CDN/tree/dev/js/intermine/apps-c/list-widgets/2.1.3

You'll want to make sure that your [global.web.properties](https://github.com/intermine/intermine/blob/dev/intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties#L127) points to 2.1.3 at the correct CDN location.

Let me know if it helps! :smile:

**Comment by kkarra** [comment]
I downloaded the zip file from here https://github.com/intermine/CDN/tree/dev

I did not change anything in global.web.properties as I swithced CDN directories..above CDN-dev/ as CDN/ 

Restarted tomcat, redeployed and cleared cache - still don't see it working.

http://yeastmine-test.yeastgenome.org/yeastmine-dev/begin.do

test genes:
YER117W YGL077C YGL103W YGR118W YHR010W YHR141C YHR143W-A 
YJL134W YJL190C YJR094W-A YKR057W YLR075W YLR332W YLR342W-A 
YLR367W YML026C YMR143W YMR221C YMR230W YMR241W YNL210W 
YOL092W YOR096W YOR196C YOR234C YOR293W YOR369C YPR132W

**Comment by yochannah** [comment]
Even though you're using the dev branch of the CDN I think you're still pointing to the old version (2.1.2) of the script. try changing to 2.1.3 in global web properties and redeploy?

**Comment by julie-sullivan** [comment]
@yochannah to get this fix in the next release, we'll update our CDN too?

**Comment by yochannah** [comment]
@julie-sullivan I've only been able to test in highly contrived example scenarios, not real-word ones. But yeah, once @kkarra confirms the update does what I hope, I'll deploy to the CDN and make a pull request to the intermine repo to update global.web.properties.

**Comment by kkarra** [comment]
It works fine now. Able to export a publication widget even null PMIDs are in the table.
