### ISSUE TITLE
Some LOOKUP strings cause a service error

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#1368]
A user was querying MouseMine for deletions on chromosome 8 using a LOOKUP constraint on SequenceFeature. She entered "Del(8_", because all chr 8 deletions begin with this string. 
The result is a "server error" message. By escaping the parenthesis "Del(8_", the search works. (Better yet, restructure the query not to depend on nomenclature - but that's another story.)

**Comment by julie-sullivan** [comment]
Works for me without a wildcard. With a wildcard I get this error:

```
java.util.regex.PatternSyntaxException: Unclosed group near index 7
del(8.*
```

This is because wildcards are treated a bit differently. We use regex to find matches, and the bracket in the search term is being processed as part of the regular expression. [Source](https://github.com/intermine/intermine/blob/dev/intermine/api/main/src/org/intermine/api/bag/BagQueryRunner.java#L204). We need to escape any special characters.
