### ISSUE TITLE
org.json jar file is old and lacks some JSON spec methods

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#1450]
The included org.json package is quite old and lacks some useful methods in the current JSON spec, for exampe: keySet() and toMap(). I suggest replacing it with a current version, which I can supply, compiled from here: https://github.com/stleary/JSON-java

intermine/intermine/model/main/lib/json20110106.jar
intermine/intermine/webservice/client/main/lib/json20110106.jar

**Comment by sammyjava** [comment]
[json20160810.zip](https://github.com/intermine/intermine/files/572644/json20160810.zip)

**Comment by julie-sullivan** [comment]
Failed Travis tests. Seems like there is some sort of Java version compatibility problem.

**Comment by justinccdev** [comment]
fwiw, here's a version compiled for java 1.7.  Name is 20161008 as this is <year><month><day> of the last change to that repo (I suspect this is the same as sammyjava but with switched month and day).

[json20161008.zip](https://github.com/intermine/intermine/files/604100/json20161008.zip)

Analysis of sammyjava's jar does show compilation for 1.8

**Comment by sammyjava** [comment]
Ahhh, sorry about that.

**Comment by justinccdev** [comment]
No worries 😊

**Comment by justinccdev** [comment]
This is being progressed under #1457.  After sorting out various issues with actually getting the right jar in, it turns out some change in JSON-java [1] is causing a couple of InterMine tests to fail.  It's not obvious when this occurred so the next step will be to divide and conquer to find out which JSON-java change is causing this and then work out what to do about it.

[1] https://github.com/stleary/JSON-java

**Comment by justinccdev** [comment]
This can't be done until the test failures on updating the jar have been fixed.

**Comment by julie-sullivan** [comment]
oh. okay. I'll take a look. Hopefully just reordering?

**Comment by justinccdev** [comment]
Unfortunately not, afair, it was something else caused by some subtle change subtly in the behaviour of JSON-java (aka json-lib).  When I last looked, I had come to the point of actually comparing json-lib source code to try and identify the change but other priorities took over.  If we're really unlucky the change was a local patch by somebody in InterMine which has since been lost.  A more fruitful approach may be to simply update the JAR and directly change the InterMine source code to accommodate the different behaviour but this won't be simple either, I think.

**Comment by julie-sullivan** [comment]
[Two test failures](https://travis-ci.org/julie-sullivan/intermine/builds/279565304)

1. imjs -- which I am guessing is related to the test failings in #1683 and #1670. imjs is handling JSON weirdly.

2. JSON row iterator test

```
FAILURE: Class org.intermine.webservice.server.output.JSONRowIteratorTest, method testResultsWithNulls

junit.framework.ComparisonFailure: null expected:<null> but was:
<[Problem with index 0:
 [Expected the keys
 [column, id, class, value, url], 
but got these: 
[column, url], 

Problem with id: org.json.JSONException: JSONObject["id"] not found., Problem with class: org.json.JSONException: JSONObject["class"] not found., 
Problem with value: org.json.JSONException: JSONObject["value"] not found.],
 Problem with index 1: [Expected the keys [column, id, class, value, url], but got these: [column, url], Problem with id: org.json.JSONException: JSONObject["id"] not found., 
Problem with class: org.json.JSONException: JSONObject["class"] not found., Problem with value: org.json.JSONException: JSONObject["value"] not found.]]>

	at org.intermine.webservice.server.output.JSONRowIteratorTest.testResultsWithNulls(JSONRowIteratorTest.java:315)

```
It's weird the other tests pass though, right?
