### ISSUE TITLE
XML queries are invalid if some constraint has a code but the first constraint does not.

### ISSUE THREAD

**Issue by joshkh** [intermine/intermine#1468]
This query errors (400 XML is not well formatted):

```xml
<query model="genomic" view="Gene.secondaryIdentifier Gene.symbol Gene.primaryIdentifier Gene.organism.name" sortOrder="">
    <constraint path="Gene" value="PL FlyAtlas_maleglands_top" op="IN" />
    <constraint path="Gene.symbol" value="intr" op="=" code="A"/>
</query>
```
Move the code from the second constraint to the first constraint and it runs successfully:
```xml
<query model="genomic" view="Gene.secondaryIdentifier Gene.symbol Gene.primaryIdentifier Gene.organism.name" sortOrder="">
    <constraint path="Gene" value="PL FlyAtlas_maleglands_top" op="IN" code="A"/>
    <constraint path="Gene.symbol" value="intr" op="=" />
</query>
```

This seems very fragile!

**Comment by julie-sullivan** [comment]
I suppose the reason for this is in the second case the query handler knows to assign the second constraint with "B". 

In the first case, because it hasn't processed the other constraints yet, the query handler doesn't know which constraint code to use.

Case 1 - this is a poorly formatted query. It is missing the constraint code. This is the correct behaviour. 

Case 2 - this is a poorly formatted query. It is missing a constraint code. HOWEVER we are being so nice and processing it anyway even though YOU made a mistake. And now you complain!

I would like to close this ticket because I don't think this needs to be addressed. @joshkh Please reopen if you want to discuss more or have strong feelers about this.
