### ISSUE TITLE
GFF3 export - not adding columns

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1515]
From yeastmine user  Wayne Decatur via @kkarra

```
 Export of a GFF3 formatted file  from YeastMine seems buggy. Specifically
 the `Columns`ability. It looks like it is set up to allow control of what is in the
 last column of a GFF file, i.e., the attributes column, but it doesn't seem to 
function as well as it could. I select GFF3 format and then go to `Columns` 
and it seems I can add `Additional` paths such as `Gene > Standard Name` 
and `Gene > Systematic Name`. And then I can toggle those choices `on`
 or `off`. But it only seems to allow me to have the last one I toggled on no 
matter if all toggled or not. Meaning it seems to only result in the DBID plus
 one other item in the attribute column. I cannot add both `Standard Name` 
and `Systematic Name` as the toggles would imply.

```

**Comment by julie-sullivan** [comment]
The Java looks okay, maybe. The problem is [Line 134](https://github.com/intermine/intermine/blob/dev/bio/webapp/src/org/intermine/bio/web/export/GFF3Exporter.java#L134). The paths are not handed to the Java from the results table.

**Comment by julie-sullivan** [comment]
Also check #227, get an error when adding collections to export. Related?

**Comment by joshkh** [comment]
IM-Tables appears to be generating the correct query when sending it to InterMine for processing. For example, I added the `Gene > symbol` and `Gene > length` attributes which produced the following GET request triggered by the `Download File` button.


```
http://localhost:8080/biotestmine/service/query/results/gff3
?query=
    <query 
        model="genomic" 
        view="Gene.id Gene.symbol Gene.length" 
        name="Bio Query" >
    </query>
&format=gff3
&start=0
&filename=Bio_Query 
```

**Comment by joshkh** [comment]
1. According to iodocs, the [`query/results/gff3`](http://iodocs.apps.intermine.org/flymine/docs#/ws-fasta-query/POST/query/results/fasta) endpoint accepts two parameters, `query` and an optional `view`.

2. Adding a single path in the `view` parameter does appear in the results.

3. ...but, using iodocs, I can't get more than two views to validate no matter how I separate them (" ", ";", ",")

4. Adding an additional attribute in the im-tables export dialogue adds the attribute to the view attribute of the `query` URL parameter above rather than an additional 'view' URL parameter. 

5. Contrary to the description at the top of this issue, I can't get any additional fields to appear (as opposed to just one extra).

Here's a test query in FlyMine with just a few results:

```
<query model="genomic" view="Gene.secondaryIdentifier Gene.symbol Gene.primaryIdentifier Gene.organism.name" >
  <constraint path="Gene" op="IN" value="esyN demo list" code="A" />
</query>
```

@julie-sullivan can you confirm how the views should be separated using iodocs? Once we figure that out I can modify im-tables to put extra columns in an additional `views` URL parameter.

**Comment by julie-sullivan** [comment]
I add view via iodocs and this is what I get:
```
 www.flymine.org/query/service/query/results/gff3?query=<query name="short genes on the X chromosome" model="genomic" view="Gene.id Gene.exons.id">
    <constraint path="Gene.chromosome.primaryIdentifier" op="=" value="X"/>
    <constraint path="Gene.length" op="&lt;" value="1000"/>
</query>&view=Gene.name 
```
Ouch!

**Comment by julie-sullivan** [comment]
```
        <param type="String[]" required="false"
            description="Extra columns to include as extra information in the ninth column"
            default="Gene.length">view</param>
```

**Comment by julie-sullivan** [comment]
It looks like the Java might be ignoring the views?

```
        List<String> viewColumns = new ArrayList<String>(pq.getView());
```

pq is the path query, so it seems like it's getting the view from the query and ignoring the view parameter.

**Comment by julie-sullivan** [comment]
```
        // Bring back original views for extra fields to be included in data export
        // NB: Functional but bad practice?
        // view in http request will look like: view=Gene.name&view=Gene.length...
        // Support the standard mechanism for accepting multiple parameter values
```
So it looks like you have `view` param for each path.

**Comment by joshkh** [comment]
Fixed by https://github.com/intermine/im-tables/commit/42d222bb0279d9d31748e4abe968dec02ff1bc44

The new version of im-tables is on the dev CDN, and since we're now using the /im-tables/2.0.x symlink then you should only have to refresh your web page to test.

**Comment by julie-sullivan** [comment]
This works!! Nice job.
