### ISSUE TITLE
MouseMine: super user genes are upgrade but show 0 genes

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1540]
From @sneuhaus and @JoelRichardson :

```
We just noticed that all the lists saved by the superuser showed ‘0 values’ in the Number Of Objects column on the MyMine Lists tab.

Some tables are in the “Lists to upgrade” table but most are not.

 

We think the same thing might be happening to other users as we have had some users wondering why their lists were gone.

 

The superuser’s tables can be upgraded and saved by using the bagUpgrade.do URL and providing the table name, this seems to fix them.

 

Any ideas what might have happened? It seems like some automagic upgrade of lists did not take place?
```

**Comment by danielabutano** [comment]
2 applications pointing to the same userprofile cause  the problems.
Presuming we have:
Application1 with serialNumber1 != serialNumber2 in userprofile
Application2 with serialNumber2 = serialNumber2 in userprofile

Then:
1. Restart Application1 -> serialNumber1 will be set in the userprofile.
2. User daniela creates list1 using the Application2. When the list is created list1 is set to CURRENT, and the osbag_int table is updated, but in the Application2 not in Application1!!!
3. Restart Application1.The serialNumbers are the same: serialNumber1 in the Application1 = serialNumebr1 in the userprofile.
4. User daniela logs in the Application1. No need to run the upgrade process, the list1 is still CURRENT. The list shows 0 items because osbag_int table, in the Application1 doesn't contain the  intermine IDs for the list1 (Application2 does).

Still investigating if there are other scenarios

**Comment by julie-sullivan** [comment]
@danielabutano If the user upgrade process were disturbed (e.g. a network error) this would NOT account for what we are seeing. 

In that case, the lists would have a to be upgraded status, not a CURRENT status.

Is that correct?

**Comment by danielabutano** [comment]
Correct! The list should be in UPGRADING status.

**Comment by danielabutano** [comment]
From @sneuhaus. After rebuilding the DB the problem has gone (as it was expected. The build updates the serialNumber, all the list are set to NOT_CURRENT)
