### ISSUE TITLE
Add search facets webservice

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#1632]
Right now there's no way to retrieve the search facets without actually performing a search. For UX/UI purposes, knowing the facets beforehand can smooth the way.

This can be partly spoofed by running a blank query with 0 results, which will return all the facets... or possibly time out because it's actually running a massive search. As such the workaround isn't really feasible or useful. 

See https://github.com/intermine/intermine-ios/issues/18#issuecomment-315061483 for how we discovered this. 

The best way to take this forward would just be to expose the names of the facets via a web service. json if possible, because json is the best.

**Comment by yochannah** [comment]
When this is done and testable on something public like beta flymine or flymine, can we please add a comment on https://github.com/intermine/intermine-ios/issues/18 ? Thanks!!

**Comment by justinccdev** [comment]
It turns out faceting doesn't keep a record of all possible phrases for a facet - this has to be built either by:

A) going through all documents in the index at runtime to build the phrase set or 
B) recording the relevant phrases at build time and have InterMine Server store that information along with the built search index.

Solution A is like the 0 result search and takes a long time (e.g. >30 secs on Flymine for Category) to retrieve.  So I think solution B is necessary, but will be a bit more work and require a mine to rebuild its search index before it is available.  

Also, so far I've only looked at the simple Category case - organisms and pathways are more complicated to perform since they are composites of multiple class field values (e.g. pathways.name is a composite of Protein.pathways and Gene.pathways).  This is much simpler to handle with solution B.  I will also need to deal with other settings (there is an index.facet.path type which is InterMIne specific and may or may not be actually used).

This is all considerable work so would take some time (possibly a couple of weeks).  So I have to ask, how useful is this information?  For category, [how/do you need] to judge which category is most important (there could be a many in a big model).  Also, some facets may have many values (e.g. in Synbiomine you would get a list with 40+ organism names, and I imagine in other mines there would be even more pathways).  How would you deal with this?

To note, neither updated Lucene or ElasticSearch appears to provide this feature.

**Comment by yochannah** [comment]
@justinccdev - I'm not sure how to quantify the usefulness of this! It would improve the user experience of the iOS app significantly for a few different reasons, particularly the way it combines search across multiple InterMines. 

For example, imagine this workflow:

1. You know you'd like to look up a gene called GATA1. You open your app, and search with the following parameters:
   - HumanMine
   - no facet (since you can't know before a search what facets are available)
   - Term: "GATA1"
2. Too much comes back, so you refine to Gene and run the search again
3. Ok, you want to look at RatMine now. Select RatMine, re-run search
4. Search results come back, unfaceted again, since we don't know if RatMine has the Gene facet. 
5. Refine to gene and search again. Arg!!

This is a use-case that both Gos and I spotted when testing the iOS app.

So I guess it's something we *should* have before we start working on any multi-mine tools, *AND* it will improve user experience even for a single intermine in, say, bluegenes, if we offer the option of pre-selecting a facet in the search page. 

If it's going to take a couple of weeks there's probably no way we can realistically have it implemented in enough mines to be useful for the iOS app before GSoC ends, though :(

**Comment by yochannah** [comment]
Oh, a better way to summarise why this is useful: batch-querying multiple mines.

I know my search term.
I know it's a protein.
But I don't know the facets available for each mine so I can't automatically search all mines with a facet at once.

This is obviously more realistic for the less common facet datatypes!

**Comment by justinccdev** [comment]
I agree this is the kind of information one wants.  Really, one would want facets to be labelled with ontology terms so one can a) know what the facet value means and b) be able to do multi-source search even if the names are slightly different (e.g. 'protein' or 'proteins').  But one could start by simply returning text strings.

**Comment by julie-sullivan** [comment]
We are going to wait on this. It's a tricky problem and requires a bit more thought.

**Comment by julie-sullivan** [comment]
@danielabutano With SOLR, will the facets in the search be available? So that we can provide them via a web service?

**Comment by julie-sullivan** [comment]
@danielabutano Looks like you can get all the buckets: https://lucene.apache.org/solr/guide/7_2/json-facet-api.html

**Comment by yochannah** [comment]
adding a further note here - this is also affecting the cross-intermine search app (currently under development as part of GSoC 2018) in the same way.

**Comment by julie-sullivan** [comment]
This is done in the Solr branch
