### ISSUE TITLE
End points have an attribute for queries called "XML". We accept JSON queries so this attribute name is becoming increasingly inaccurate.

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1676]
@joshkh @justinccdev @danielabutano @yochannah @sergiocontrino 

See #1327 

These end points have an `XML` parameter that contains the query:

```
query/upload
template/upload
user/queries (POST)
```

These end points now accept JSON queries. 

1. Putting JSON as a value for a parameter called `xml` is daft.
2. Changing a parameter name is not backwards compatible! Bad practice!

**Proposed Solution**

1. Change the parameter name to be `query`
2. Release in InterMine 2.0
3. Blog post, give lots of notice for change
4. Most people use the clients, not the raw HTTP calls. These end points are not used in the clients (I don't think?). `/sequence` is/was used by @JoeCarlson however
5. Blue genes would have to adapt. But older mines won't work with blue genes anyway!

What are your thoughts?

There isn't a perfect solution, we need to pick the one that is least bad.

**Comment by justinccdev** [comment]
I think we need an inputformat parameter as well.

Previously, and in another context (query/results, I think?) I thought that we could get away with requiring InterMine to work out the query format.  Whilst this is relatively simple for InterMine XML vs InterMine JSON, I think now that we will run into trouble when we need to support other formats in the future.

For instance, GraphQL [1] is a query language quickly gaining in popularity (promoted by Facebook, and some of the recent NIH Data Commons proposals talked about using it).  It's surprisingly reminiscent of PathQuery, so could probably be realistically supported by InterMine.

However, it will also almost certainly be expressed as a JSON structure.  Telling the difference between InterMine JSON and GraphQL JSON will be much more difficult than XML vs JSON.  Even the InterMine JSON format itself could change just as InterMine XML has in the past (as shown by the outdated xml version parameter on some of these endpoints).  And there is also Cypher, SPARQL or other things that may also come along in the future.

So I think better to add an inputformat parameter now so that we never need to change these endpoints again.  For instance, to cover InterMine XML, InterMine JSON and GraphQL JSON, Cypher and SPARQL as above we could have, respectively

```
inputformat=xml
inputformat=json
inputformat=graphql
inputformat=cypher
inputformat=sparql
```

The plain 'xml' and 'json' denote InterMine's native XML and JSON query format, which I think is reasonable, though one could also do things like 'im-xml' and 'im-json'.

This is extensible and prevents InterMine code complexity, at the small cost of requiring the client to specify inputformat (which they always know).

[1] http://graphql.org/

**Comment by julie-sullivan** [comment]
These three are NOT used in the clients or in the iOS app. So safe to change.

Keeping the `xml` parameter would be safest, and adding `query` and using whichever one was populated. Can you deprecate individual attributes?

**Comment by justinccdev** [comment]
I had a brief look in I/O docs (which we currently use, though this appears to be a fork by Alex with unknown changes), but no obvious way to show attributes as deprecated.  Open API Specification (as implemented by Swagger, which is something we probably want to adopt eventually) will allow you to deprecate attributes in its next spec version [1] but doesn't have a way as of 2.0.

Either we'll have to just document this in the parameter description body or not worry about deprecation.

[1] https://github.com/OAI/OpenAPI-Specification/issues/701

**Comment by julie-sullivan** [comment]
Options:

1. Leave `xml` as the parameter name
2. Add `query`, deprecate `xml`
3. Change to `query`

We decided on option 3.

In the Python client (the only place this end point is used), we will check for the mine version and use the correct parameter based on that. `query` for mines 2.+ and `xml` for mines < `2.0`. It's not a great solution but it's the best one.
