### ISSUE TITLE
Case matching in ID resolver produces unexpected results

### ISSUE THREAD

**Issue by joshkh** [intermine/intermine#1731]
When resolving the identifier `pen` in FlyMine via the UI or the web services without case matching (default), we get a single matching result:

```
type: "Gene"
extra: "D. melanogaster"
identifiers: ["pen"]
caseSensitive: false
```

Now with case matching...
```
type: "Gene"
extra: "D. melanogaster"
identifiers: ["pen"]
caseSensitive: true
```
We get two synonyms that need to be resolved: Pen, pang.

![image](https://user-images.githubusercontent.com/4752532/33720046-a54c39c4-db5a-11e7-81e6-cff87836996f.png)

The case matching seems to be backwards?

**Comment by julie-sullivan** [comment]
Here's why this happens:

**NOT CASE SENSITIVE**

1. searches gene identifiers.
2. finds `Pen` gene, returns that. 

When the match is on a gene symbol like this, we are pretty sure this is the gene the user wanted so return that without searching for synonyms.

**CASE SENSITIVE**

1. searches gene identifiers.
2. finds `Pen` but doesn't match because wrong case
3. searches gene synonyms
4. finds `pen` as a synonym for both `Pen` and `Peng`

Since they are synonyms, we don't know which gene is the one the user wants so we return both.

We don't return the first synonym we find, we return all.
