### ISSUE TITLE
Need old integrate/resources/organism_config.properties functionality

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#1790]
Users need to be able to enter hitherto unknown taxonIds for extremely rare and bizarre species. Like beans. :)

Old location: mymine/integrate/resources/organism_config.properties
New location: mymine/dbmodel/resources/organism_config.properties

**Comment by julie-sullivan** [comment]
This file lists all the organisms and associated abbreviations: [organism_config.properties](https://github.com/intermine/intermine/blob/dev/bio/core/main/resources/organism_config.properties)

The [OrganismRepository](https://github.com/intermine/intermine/blob/dev/bio/core/main/src/org/intermine/bio/util/OrganismRepository.java#L67) uses this file to convert from organism name to taxon ID.

Sam has his own organism_config.properties file that he uses instead of the one provided. He doesn't want to put those taxons in the main file (why was that again?). The code will use the config file in the JAR. How do we replace that file with the file in `mymine/dbmodel/resources/`? 

Do we want to merge the files or overwrite?

**Comment by julie-sullivan** [comment]
This is a blocking issue because Sam can't use certain data sources without having the organism lookup.

**Comment by julie-sullivan** [comment]
1. Add a task to the integrate plugin 
2. task should copy the file to the local build directory and rename it 
3. update the organism repository to use the renamed file
4. if file is already there, use that instead of default file.

**Comment by julie-sullivan** [comment]
@sammyjava I can't find the code where this file is used on the dev branch. Do you want your organism config file to overwrite the default one? Or do you want them merged?

**Comment by julie-sullivan** [comment]
Both the `organism_config.properties` files are in the classpath but the build is using the first one it finds, the default one in the `bio-core.jar`. Instead, let's rename the local file and update the code to look for the custom file first then the default file.

**Comment by sammyjava** [comment]
Yeah, no need to merge, right now it uses the local file in lieu of the core version. The reason for not adding more legumes to the core file is that there will surely be sundry IM users in the future that are making mines for all sorts of hitherto unknown organisms (maybe newly discovered!) and there needs to be a way for users to augment/replace the core list.

**Comment by sammyjava** [comment]
I'm trying to build with 2.0 again, now that the postprocess refactor is all set and I've got my sources and postprocess and the db built. So this issue is what's hanging me up from building a mine at this point. :)

**Comment by sammyjava** [comment]
I left a comment on the commit about not being able to get gradle to look under `resources` for `organism_config.properties`
