### ISSUE TITLE
gradle task buildDB should depend on clean

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#1825]
This keeps hitting me upside the head: I change my data model in my sources, I do an install of the new sources, then I go to the mine and do a `gradlew buildDB`. But, nope, the OLD data model is still in there. I have to do a `gradlew clean` before the `buildDB`. I say `buildDB` should do a full clean first.

**Comment by julie-sullivan** [comment]
@sammyjava Interesting comment!! This is the behaviour from `ant`, so that's why it's the way it is now. I agree, most of the time when you run a `builddb` you want to do a `clean` first.

However, I can see a use case for NOT doing a `clean` with a `builddb`. For example, clean deletes the cached files -- the ID resolver and publications.xml for example. The `publications.xml` file can take a few hours to generate so you might want to keep.

So it's easy to do a clean + builddb, but if you won't want to do a `clean` and we include it in `builddb`, that might make people's lives more difficult.

What do you think?

**Comment by sammyjava** [comment]
Fine with me. Since you CAN get broken behavior without the clean (whenever you update your local model, because buildDB doesn't replace it), I figured clean is, technically, a requirement. But I'm happy to clean manually. In that case, though, there should be huge letters somewhere IF YOU CHANGE YOUR DATA MODEL (which sammyjava does constantly) BE SURE TO RUN THE clean TASK BEFORE buildDB ELSE YOU WILL NOT UPDATE THE MINES MODEL! :)

**Comment by sammyjava** [comment]
(I'll let you ponder that one more time before I close this.)

**Comment by julie-sullivan** [comment]
Would printing that message to the console help? because you are right, it is a big issue!

**Comment by sammyjava** [comment]
Sure, something to let people know why their mine is broken after they did a data model update. :)

**Comment by julie-sullivan** [comment]
Done! Thanks @sammyjava I really appreciate the suggestion. These kinds of small things really make InterMine just a bit easier to use, and I need to do more of.

**Comment by sammyjava** [comment]
Oh, hush, you do a great job!
