### ISSUE TITLE
Solr: search for OR

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#1854]
if I search for OR, the gene with symbol "or" should be displayed.
This doesn't work in the current system too. See http://www.flymine.org/flymine/report.do?id=1025580

**Comment by arunans23** [comment]
The reason this is not working in the current system is because, the word "or" is explicitly made uppercase while manipulating the [query](https://github.com/intermine/intermine/blob/gradle/intermine/api/src/main/java/org/intermine/api/lucene/KeywordSearch.java#L785). 

But I am not doing such thing. So it should work in solr case.

**Comment by danielabutano** [comment]
@arunans23 I will test it with flymine

**Comment by danielabutano** [comment]
@arunans23 in biotestmine the serach for the term or works, bit for the term OR returns an exception
