### ISSUE TITLE
Solr: XML library conflicts with the default InterMine one, so has to be set manually.

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#1889]
To serialize xml content, we use [XMLOutputFactory](https://github.com/intermine/intermine/blob/dev/intermine/pathquery/main/src/org/intermine/template/xml/TemplateQueryBinding.java#L124) which loads the class `com.sun.xml.internal.stream.XMLOutputFactoryImpl` at runtime.

In the `gradle-solr` branch, we've added solrj dependency, which depends on `woodstox-core-asl`. The `XMLOutputFactory` loads the class `com.ctc.wstx.stax.WstxOutputFactory` (which uses `com.ctc.wstx.sw.SimpleNsStreamWriter` that doesn't work properly) , instead of `XMLOutputFactoryImpl`.

Looking at the [java doc](https://github.com/infobip/infobip-open-jdk-8/blob/master/jaxp/src/javax/xml/stream/XMLOutputFactory.java#L142), it's possible to configure a system property specifying which `XMLOutputFactory` has to be used.

In `biotestmine`, in the `gradle.properties`, I have added:

```
systemProp.javax.xml.stream.XMLOutputFactory = com.sun.xml.internal.stream.XMLOutputFactoryImpl 
```

This fixed the issue which didn't allow the `LoadDefaultTemplates` to save the templates into the userprofile database.

**Comment by julie-sullivan** [comment]
That all sounds good! Can you explain what needs to be fixed?

If I remember correctly, it was the tests failing? Or was there something else?

**Comment by julie-sullivan** [comment]
Okay thanks, I will fix the tests, and test the XML export as well.

**Comment by julie-sullivan** [comment]
99% of the object store tests are passing.

Here's what I have so far:

**EXPECTED**

```
<{precomp_3_orderby_field=CREATE INDEX precomp_3_orderby_field ON precomp_3 USING btree (orderby_field), precomp_3_lower_a4__=CREATE INDEX precomp_3_lower_a4__ ON precomp_3 USING btree (lower(a4_)), precomp_3_lower_a3__=CREATE INDEX precomp_3_lower_a3__ ON precomp_3 USING btree (lower(a3_)), precomp_3_a1_id__lower_a3____lower_a4__=CREATE INDEX precomp_3_a1_id__lower_a3____lower_a4__ ON precomp_3 USING btree (a1_id, lower(a3_), lower(a4_)), precomp_3_lower_a4___text_pattern_ops=CREATE INDEX precomp_3_lower_a4___text_pattern_ops ON precomp_3 USING btree (lower(a4_) text_pattern_ops), precomp_3_lower_a3___text_pattern_ops=CREATE INDEX precomp_3_lower_a3___text_pattern_ops ON precomp_3 USING btree (lower(a3_) text_pattern_ops)}> but was:
```

**ACTUAL**

```

<{precomp_3_lower_a4__=CREATE INDEX precomp_3_lower_a4__ ON public.precomp_3 USING btree (lower(a4_)), precomp_3_orderby_field=CREATE INDEX precomp_3_orderby_field ON public.precomp_3 USING btree (orderby_field), precomp_3_lower_a3__=CREATE INDEX precomp_3_lower_a3__ ON public.precomp_3 USING btree (lower(a3_)), precomp_3_a1_id__lower_a3____lower_a4__=CREATE INDEX precomp_3_a1_id__lower_a3____lower_a4__ ON public.precomp_3 USING btree (a1_id, lower(a3_), lower(a4_)), precomp_3_lower_a4___text_pattern_ops=CREATE INDEX precomp_3_lower_a4___text_pattern_ops ON public.precomp_3 USING btree (lower(a4_) text_pattern_ops), precomp_3_lower_a3___text_pattern_ops=CREATE INDEX precomp_3_lower_a3___text_pattern_ops ON public.precomp_3 USING btree (lower(a3_) text_pattern_ops)}>

```

_Looks_ the same? Just out of order, which maybe using a different XML library would do that?

**Comment by julie-sullivan** [comment]
bio test still failing, but this test doesn't use XML.

```
Caused by: java.io.FileNotFoundException: /home/travis/build/julie-sullivan/intermine/bio/build/obo8758667583866099347.tmp (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at org.intermine.bio.ontology.OboParser.processRelations(OboParser.java:146)
	at org.intermine.bio.ontology.SequenceOntology.process(SequenceOntology.java:737)
	... 45 more
```

**Comment by julie-sullivan** [comment]
Okay that's a dumb idea, I should revert it.

There is no way to get a system property from Gradle to Java at runtime in our webapp. 

Instead, we need to set that system property in Java.

**Comment by julie-sullivan** [comment]
@danielabutano Can you test my `solr` branch? 

1. merged dev branch into @arunans23's `gradle-search` branch and then made a `solr` branch in my repo to test.
2. sequence ontology test still failing. Will investigate
3. I added the XML property to each `grade.properties` file:

```
# added to each gradle.properties file
systemProp.javax.xml.stream.XMLOutputFactory=com.sun.xml.internal.stream.XMLOutputFactoryImpl
```
4. For `test` tasks, I added this to each `build.gradle` file so that the system property would be transferred to Java and available for the tests. Tests are passing now (except for the sequence ontology tests, don't know why, look unrelated??)

```
        // we have a system property that we need to get to the tests
        systemProperties System.properties
```

5. For the main code, I added a property to `global.web.properties`. This property is read in  `InitialiserPlugin.java` and set to be a system property so the webapp can access. XML import / export seem to work fine now.

6. I was going to put in `default.intermine.properties` but that right now only has properties for the database and objectstore. Maybe you don't agree?

7. I ran two sources with XML and it loaded correctly.

8. `InitialiserPlugin.java` might not be the best place to set this system property. However, in the other packages (e.g. intermine-objectstore) we don't need this property because SOLR is not on the classpath and we don't have the conflict. Also, web services currently do not work without a webapp so this is also safe. 

Maybe. I'd feel better if you reviewed!!

**Comment by danielabutano** [comment]
I've tested the solr branch locallly only for build the webapp. I have done some tests (search, run query, export xml results, export xml query, export xml template ) and everything seems working well.
Maybe the default.intermine.properties it's a better place for setting systemProp.javax.xml.stream.XMLOutputFactory but also global.web.properties is ok.
Let me know if you want me test also beta.flymine.org.

**Comment by julie-sullivan** [comment]
@danielabutano Thanks! I will leave SOLR up as beta flymine a while (whilst I work on fixing those tests) and ask Yo and Rachel to do extra testing. I'll run a build too.
