### ISSUE TITLE
Decorate the model with ontology terms (where possible)

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1935]
We want to assign an ontology term for each entry in the data model, e.g.:

```
<class name="Gene" extends="SequenceFeature" is-interface="true" URI="http://purl.obolibrary.org/obo/SO_0000704">
```

For sequence features we can use the SO ontology. For other types in the data model, we can use another general ontology. Maybe Semantic Science? @rachellyne ?

For the core data model, the URIs can be generated and stored in a data file. We only change SO obo versions rarely (once) so this is acceptable.

How to deal with custom data classes will be another ticket.

**Comment by sammyjava** [comment]
There's a lot of stuff in SO that isn't sequence features. For example, http://www.sequenceontology.org/browser/current_svn/term/SO:0000018 ... in fact, most of my genetic objects are in SO. Even QTL (http://www.sequenceontology.org/browser/current_svn/term/SO:0000771) because it *can* be related to a sequence region.

**Comment by julie-sullivan** [comment]
Thanks that's helpful Sam! Maybe SO can handle more than I think.
