### ISSUE TITLE
Fix protein atlas displayer in humanmine

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1988]
On our last build, the protein atlas displayer stopped working. The labels changed and it was all crazy. I didn't have time to fix, so [I commented it out.](https://github.com/intermine/humanmine/blob/master/webapp/src/main/webapp/WEB-INF/webconfig-model.xml#L443)  but I would like to fix for the workshop.

Here is the query the displayer is running:

```
<query name="" model="genomic" view="Gene.primaryIdentifier Gene.proteinAtlasExpression.cellType Gene.proteinAtlasExpression.level Gene.proteinAtlasExpression.reliability Gene.proteinAtlasExpression.tissue.name Gene.proteinAtlasExpression.tissue.tissueGroup.name" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene" op="LOOKUP" value="pparg" extraValue=""/>
</query>
```
Here are the JSPs

[proteinAtlasDisplayer.jsp](https://github.com/intermine/intermine/blob/dev/bio/webapp/src/main/webapp/model/proteinAtlasDisplayer.jsp)

[proteinAtlasDisplayerTable.jsp](https://github.com/intermine/intermine/blob/dev/bio/webapp/src/main/webapp/model/proteinAtlasDisplayerTable.jsp)

@rachellyne @yochannah Where should I start?

**Comment by yochannah** [comment]
@julie-sullivan where's the code that passes the query to the jsp? Something's definitely wired up wrong - see this screenshot - the tissue type is outputting from the reliability property, and nothing else is defined except expressiontype. 

![image](https://user-images.githubusercontent.com/9271438/53569930-29281200-3b5d-11e9-86fb-5192810a3f9d.png)

We know the data are okay, because a results table outputs it correctly (see below), so I presume there's some java code providing the query to the jsp that is mapping columns to the wrong thing?

![image](https://user-images.githubusercontent.com/9271438/53569973-4361f000-3b5d-11e9-9eaa-abe73191dc83.png)


([code to output all fields](https://stackoverflow.com/a/24576688/1542891) thanks to [Toby](https://stackoverflow.com/users/1230910/toby) via stackoverflow.)

**Comment by julie-sullivan** [comment]
This is where the query is done: [ProteinAtlasDisplayer.java](https://github.com/intermine/intermine/blob/dev/bio/webapp/src/main/java/org/intermine/bio/web/displayer/ProteinAtlasDisplayer.java) which seems to use this class for results: [ProteinAtlasExpressions.java](https://github.com/intermine/intermine/blob/dev/bio/webapp/src/main/java/org/intermine/bio/web/model/ProteinAtlasExpressions.java)

**Comment by julie-sullivan** [comment]
```
]102604 [ajp-nio-8009-exec-55] ERROR org.intermine.web.displayer.ReportDisplayer  - Error rendering report displayer class org.intermine.bio.web.displayer.ProteinAtlasDisplayer for Gene(1221653): java.lang.NullPointerException
        at org.intermine.bio.web.model.ProteinAtlasExpressions$ExpressionType.<init>(ProteinAtlasExpressions.java:155)
        at org.intermine.bio.web.model.ProteinAtlasExpressions.<init>(ProteinAtlasExpressions.java:133)
        at org.intermine.bio.web.displayer.ProteinAtlasDisplayer.display(ProteinAtlasDisplayer.java:85)
        at org.intermine.web.displayer.ReportDisplayer.execute(ReportDisplayer.java:62)
        at org.intermine.web.struts.ReportDisplayerController.execute(ReportDisplayerController.java:43)

```

**Comment by julie-sullivan** [comment]
```
  <div class="table byCells inactive ${expressionType.clazz}">
    <c:set var="tableRows" value="${expressions.byCells}" />
    <tiles:insert page="proteinAtlasDisplayerTable.jsp">
      <tiles:put name="rows" beanName="tableRows" />
    </tiles:insert>
  </div>

  <div class="table byLevel inactive ${expressionType.clazz}">
    <c:set var="tableRows" value="${expressions.byLevel}" />
    <tiles:insert page="proteinAtlasDisplayerTable.jsp">
      <tiles:put name="rows" beanName="tableRows" />
    </tiles:insert>
  </div>
```

`Expression type` doesn't exist anymore.

**Comment by julie-sullivan** [comment]
thanks yo!!!!!!!!!! fixed in beta, will be in next release.
