### ISSUE TITLE
The operation was a success, but the patient died: creating solr index fails but gradlew reports success.

### ISSUE THREAD

**Issue by JoeCarlson** [intermine/intermine#2120]
Here is the screen output of my solr index creation error. I'll work on why the index creation failed. What I'm more perplexed by is why gradle reported a successful operation

[solr_error.txt](https://github.com/intermine/intermine/files/3687590/solr_error.txt)

**Comment by danielabutano** [comment]
Thanks @JoeCarlson for adding the ticket. 
I think that the CreateSerachIndexTask should throw a BuildingException [here](https://github.com/intermine/intermine/blob/dev/intermine/webtasks/src/main/java/org/intermine/web/task/CreateSearchIndexTask.java#L121)

**Comment by danielabutano** [comment]
Hi @JoeCarlson, instead of throwing an exception and ending the build with the BUILD FAILED message we decided to add a clearer message on the console and end with BUILD SUCCESSFUL.
If there is any solr issue, as it is in this case, the user doesn't have to re-do the build (BUT only re-run the post-process which dosn't involves the production db) and putting BUILD FAILED might make the user think to re-do the build!!!

**Comment by JoeCarlson** [comment]
As a side note, I found out the source of the underlying 'request entity too large' error. We have an nginx proxy sitting in front of our solr server. Nginx has a default 1M post size. That was easy to increase in the conf file and solves that problem.

**Comment by danielabutano** [comment]
Good to know! Thanks @JoeCarlson for sharing
