### ISSUE TITLE
Update to Java11

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#2127]

**Comment by yochannah** [comment]
:+1: This will be very useful!  

This will make biotestmine and testmine travis scripts much easier to run - right now they have to run on very old ubuntu images in order to get Java 8 running properly, but this creates _other_ dependency problems, e.g. the images don't have up-to-date enough python dependencies. See the pypy failures here: https://travis-ci.org/intermine/intermine-ws-python

**Comment by asherpasha** [comment]
I have tested ThaleMine with InterMine 4.1.1 and Gradle 4.9. It builds with both Java 8 and Java 11. Thank you for fixing the bugs.

**Comment by danielabutano** [comment]
It's great! I had tested only with biotestmine but knowing that it works with Thalemine too it's very useful. Thanks!

**Comment by danielabutano** [comment]
we need to update travis too.
in .travis.yml set openjdk11

**Comment by sergiocontrino** [comment]
tested also with the travis update.
