### ISSUE TITLE
WebProperties WS returns blugeens properties too

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#2402]

**Comment by uosl** [comment]
Bluegenes doesn't have a database, and its config file is specific to the Bluegenes deployment. BG is a client of Intermine, and any customisation should be available to all BG's that connect to a mine. If BG were to have its own properties file, these would be specific to the deployment, and not available to other BG instances.

WS bluegenes-properties uses the mine's userprofile database, which means they are available to any other BG connecting to the mine. However, due to the nature of databases, it's only practical to make changes using BG itself. For use cases where it makes more sense to edit a plaintext configuration/properties file, web.properties is a good fit.

**Comment by danielabutano** [comment]
e.g.
project.news = http://intermineorg.wordpress.org
project.rss = https://intermineorg.wordpress.com/feed/
project.url.aboutUs = http://intermine.org/about-intermine/
project.url.privacyPolicy = http://intermine.org/privacy-policy/
project.url.github = https://github.com/intermine/
project.url.discord = http://chat.intermine.org/
project.url.twitter = https://twitter.com/intermineorg
project.supportEmail = support@intermine.org
