### ISSUE TITLE
Remove legacy db types

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/intermine#485]
We have db storage types lying around like "flat mode", "noNotXML", et al. These should all go since:
  * No one uses them
  * They add complexity.

**Comment by julie-sullivan** [comment]
@rnsmith We should get rid of truncated mode. Are there others we can get rid of? We should also document flat mode a bit.

**Comment by rnsmith** [comment]
Some new documentation on objectstore O/R mapping modes: http://intrac.flymine.org/wiki/ObjectStoreModes

**Comment by rnsmith** [comment]
Truncated mode should be removed. This requires some changes to `DatabaseSchema.java` and a few simplifications in `SqlGenerator.java` (look for calls to `DatabaseSchema.isTruncate()`) and `ResultsConverter.java` (look for `objectclass`), maybe some other places as well.

The problem in doing this is with the tests.  There are tests for 'flat mode' sql generation and objectstore, but flat mode requires that there is no inheritance in the data model. The current flat mode tests truncate all classes in the testmodel that have inheritance, which also makes the tests very confusing as they combine flat mode and truncated classes.

A solution may be to create an alternative model for testing flat mode that includes the core classes (Company, Department, Employee, etc) without inheritance but so that the standard suite of test queries still work.
