### ISSUE TITLE
Export broken in cytoscape viewer

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#717]

**Comment by joshkh** [comment]
Fixed: e7827ced5d7c8389191ac8522d775bfdc5d34353 in branch [cytoscape](https://github.com/intermine/intermine/tree/cytoscape)

Root cause:
Adobe applied a security update to Flash that prevents its sandbox from sending HTTP requests with headers. This removed feature is required by CytoscapeWeb's exportNetwork() function.

Solution:
Use CytoscapeWeb's individual export functions to return its network data as a Base64 encoded string and then export it via the browser using blobs.

Caveats:
This will only work on modern browsers (ie10+).
