### ISSUE TITLE
Tomcat 8

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#745]
Errors when deploying to Tomcat 8

**Comment by julie-sullivan** [comment]
http://www.oracle.com/webfolder/technetwork/jsc/xml/ns/javaee/index.html#7
" This table contains the XML Schema components for Java EE 7 schema. All new schemas are in the http://xmlns.jcp.org/xml/ns/javaee/ namespace. Most older schemas remain in the http://java.sun.com/xml/ns/javaee/ namespace. "

We need to update web.xml to reference `web-app_3_1.xsd`

**Comment by julie-sullivan** [comment]
@justinccdev I've reassigned this to you. I was able to get Tomcat 8 to work but there was a constant 30 second delay regardless of the type of request made. I'm hoping #1113 will fix it.

**Comment by justinccdev** [comment]
I also get the same delay failure, #1113 does not change this.

However, I determined that this is being caused by the CompressingFilter in the webapp web.xml.  If you comment out use of the filter like so

```
 <filter>
  <filter-name>CompressingFilter</filter-name>
  <filter-class>com.planetj.servlet.filter.compression.CompressingFilter</filter-class>
 </filter>

<!--
 <filter-mapping>
  <filter-name>CompressingFilter</filter-name>
  <url-pattern>/*</url-pattern>
 </filter-mapping>
 -->
```

So it looks like com.planetj.servlet.filter.compression.CompressingFilter, which I believe gzips responses, is not compatible with Tomcat 8.  Our version is labelled as 1.7 and on a quick Google it doesn't look like there is a later one available.

I would remove the filter entirely and using compression at the Tomcat level instead, by setting compression="on" in the http/ajp connector in server.xml [1].  However, this would require installers to choose and do it themselves, rather than doing it automatically at the webapp level.  

What do you think?

[1] https://tomcat.apache.org/tomcat-8.0-doc/config/http.html#Standard_Implementation

**Comment by julie-sullivan** [comment]
Great detective work!! Yes, let's do as you recommend. Devs have to configure Tomcat anyway, so one more setting isn't going to hurt anyone.

**Comment by justinccdev** [comment]
#1157
