### ISSUE TITLE
Issues with Date data type

### ISSUE THREAD

**Issue by sneuhaus** [intermine/intermine#812]
Other than java.util.Date being a valid type, I couldn't find any documentation on creating date attributes. 
They can be created using a millisecond time stamp. Maybe some other format works?
Once in the database they are nicely formatted in the webapp.
Dates can't be constrained in the query builder (no popup for constraints appears).
Dates don't seem to sort correctly in the datatables.

**Comment by justinccdev** [comment]
On the load side, FullParser.populateObject() converts an Item XML entry into a FastPathObject (the Java type required for loading into an ObjectStore).

This in turn uses TypeUtil.stringToObject() to perform the conversion.  On line 780, if the date is a number then it makes the following parse attempts

1.  If the value is a number then it assumes this is Unix epoch seconds and converts accordingly
2.  Otherwise it attempts to parse this with format 'yyyy-MM-dd HH:mm:ss' UTC 
3.  Otherwise it attempts to parse this with format 'yyyy-MM-dd' UTC
4.  Otherwise it throws a RuntimeException

I don't see why we couldn't support more date input formats.  What did you have in mind?

**Comment by justinccdev** [comment]
Notifying @JoelRichardson

**Comment by julie-sullivan** [comment]
See #819
