### ISSUE TITLE
InterMine leaks like a sieve

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/intermine#860]
InterMine's heap is very leaky indeed:

![tomcat-heap](https://cloud.githubusercontent.com/assets/436846/5288978/cc44a188-7b31-11e4-839e-403cc1929efe.png)

**Comment by cmdcolin** [comment]
I started using this for memory monitoring http://www.mkyong.com/tomcat/jconsole-jmx-remote-access-on-tomcat/ but i'm still curious about the tool you use.

I have also been tweaking the setenv parameters noticed the need to add -Dorg.apache.el.parser.SKIP_IDENTIFIER_CHECK=true in tomcat7. Will probably keep adjusting as things come up

**Comment by rnsmith** [comment]
The PermGen out of memory issues should be fixed in InterMine 1.4. 

Although tomcat still reports a memory leak only weak references are retained which do get removed once a full garbage collection is carried out. I've redeployed a webapp tens of times without getting PermGen errors.  Additional tomcat settings are also required to force cleanup of Timer threads created by some libraries we use.
