### ISSUE TITLE
Need way of referring to lists stably

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/intermine#961]
Changing a list name breaks queries. Staircase depends on such queries in its histories. We should have a stable identifier in addition to the name which is immutable. Both identifiers should work in queries.

**Comment by julie-sullivan** [comment]
Other options:

1. warn people that their queries and histories will be broken
2. update the queries / histories with new name

**Comment by julie-sullivan** [comment]
@joshkh I don't know that it's a good idea to use the database ID. Will this cause problems later when we use database replication etc. 

Changing the list name will break histories, but can we do something about that? Maybe the history is what people are going to be renaming anyway since we won't have a list analysis page anymore.

**Comment by joshkh** [comment]
This is mostly a problem when someone renames a list from outside Steps using the current UI. Since the histories refer to the lists by name then Steps will lose all references. 

What do you think about adding a new attribute - some UUID that never changes but isn't the database ID?

Users can still query by list name and we'll provide the UUID as well for use by more complicated applications.

**Comment by julie-sullivan** [comment]
Not relevant for blue genes.

**Comment by julie-sullivan** [comment]
Relevant for blue genes.

**Comment by julie-sullivan** [comment]
fixed partially by #1633. Still need to identify private lists.
